// Configuration file for Secure Automation Script Generator

// Project Settings
val projectName = "SecureAutomationScripts"
val authorName = "Your Name"
val scriptExtension = ".sh" // or .bat, .py, etc.

// Security Settings
val encryptionAlgo = "AES-256-CBC" // or "RSA", "SHA-256", etc.
val encryptionKey = "your_secret_key_here"
val passwordHashing = "BCrypt" // or "SHA-256", "Argon2", etc.

// Automation Script Settings
val scriptType = "bash" // or "powershell", "python", etc.
val scriptTimeout = 300 // in seconds

// Input/Output Settings
val inputFormat = "JSON" // or "XML", "CSV", etc.
val outputFormat = "JSON" // or "XML", "CSV", etc.

// Logging Settings
val logLevel = "INFO" // or "DEBUG", "WARNING", "ERROR"
val logFilepath = "/path/to/log/file.log"

// Whitelisted Commands
val allowedCommands = listOf("ls", "cd", "mkdir", "echo")

// Blacklisted Commands
val disallowedCommands = listOf("rm", "sudo", "ssh")

// Additional Settings
val scriptHeader = """#!/bin/bash
# Generated by Secure Automation Script Generator"""
val scriptFooter = "echo \"Script execution completed.\""